//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication.CalorieCalculatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap")]
    public interface CalorieCalculatorServiceSoap {
        
        // CODEGEN: Generating message contract since element name actionType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCalories", ReplyAction="*")]
        FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponse CalculateCalories(FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCalories", ReplyAction="*")]
        System.Threading.Tasks.Task<FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponse> CalculateCaloriesAsync(FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateCaloriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateCalories", Namespace="http://tempuri.org/", Order=0)]
        public FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequestBody Body;
        
        public CalculateCaloriesRequest() {
        }
        
        public CalculateCaloriesRequest(FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateCaloriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double duration;
        
        public CalculateCaloriesRequestBody() {
        }
        
        public CalculateCaloriesRequestBody(string actionType, double weight, double duration) {
            this.actionType = actionType;
            this.weight = weight;
            this.duration = duration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateCaloriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateCaloriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponseBody Body;
        
        public CalculateCaloriesResponse() {
        }
        
        public CalculateCaloriesResponse(FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateCaloriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculateCaloriesResult;
        
        public CalculateCaloriesResponseBody() {
        }
        
        public CalculateCaloriesResponseBody(double CalculateCaloriesResult) {
            this.CalculateCaloriesResult = CalculateCaloriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalorieCalculatorServiceSoapChannel : FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalorieCalculatorServiceSoapClient : System.ServiceModel.ClientBase<FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap>, FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap {
        
        public CalorieCalculatorServiceSoapClient() {
        }
        
        public CalorieCalculatorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalorieCalculatorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalorieCalculatorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalorieCalculatorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponse FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap.CalculateCalories(FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest request) {
            return base.Channel.CalculateCalories(request);
        }
        
        public double CalculateCalories(string actionType, double weight, double duration) {
            FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest inValue = new FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest();
            inValue.Body = new FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequestBody();
            inValue.Body.actionType = actionType;
            inValue.Body.weight = weight;
            inValue.Body.duration = duration;
            FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponse retVal = ((FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap)(this)).CalculateCalories(inValue);
            return retVal.Body.CalculateCaloriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponse> FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap.CalculateCaloriesAsync(FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest request) {
            return base.Channel.CalculateCaloriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesResponse> CalculateCaloriesAsync(string actionType, double weight, double duration) {
            FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest inValue = new FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequest();
            inValue.Body = new FitnessApplication.CalorieCalculatorServiceReference.CalculateCaloriesRequestBody();
            inValue.Body.actionType = actionType;
            inValue.Body.weight = weight;
            inValue.Body.duration = duration;
            return ((FitnessApplication.CalorieCalculatorServiceReference.CalorieCalculatorServiceSoap)(this)).CalculateCaloriesAsync(inValue);
        }
    }
}
