//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication.StepGoalsReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StepGoalsReference1.StepGoalsSoap")]
    public interface StepGoalsSoap {
        
        // CODEGEN: Generating message contract since element name activityLevel from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecommendedSteps", ReplyAction="*")]
        FitnessApplication.StepGoalsReference1.RecommendedStepsResponse RecommendedSteps(FitnessApplication.StepGoalsReference1.RecommendedStepsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecommendedSteps", ReplyAction="*")]
        System.Threading.Tasks.Task<FitnessApplication.StepGoalsReference1.RecommendedStepsResponse> RecommendedStepsAsync(FitnessApplication.StepGoalsReference1.RecommendedStepsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecommendedStepsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecommendedSteps", Namespace="http://tempuri.org/", Order=0)]
        public FitnessApplication.StepGoalsReference1.RecommendedStepsRequestBody Body;
        
        public RecommendedStepsRequest() {
        }
        
        public RecommendedStepsRequest(FitnessApplication.StepGoalsReference1.RecommendedStepsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecommendedStepsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string activityLevel;
        
        public RecommendedStepsRequestBody() {
        }
        
        public RecommendedStepsRequestBody(int age, string activityLevel) {
            this.age = age;
            this.activityLevel = activityLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecommendedStepsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecommendedStepsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FitnessApplication.StepGoalsReference1.RecommendedStepsResponseBody Body;
        
        public RecommendedStepsResponse() {
        }
        
        public RecommendedStepsResponse(FitnessApplication.StepGoalsReference1.RecommendedStepsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecommendedStepsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecommendedStepsResult;
        
        public RecommendedStepsResponseBody() {
        }
        
        public RecommendedStepsResponseBody(string RecommendedStepsResult) {
            this.RecommendedStepsResult = RecommendedStepsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StepGoalsSoapChannel : FitnessApplication.StepGoalsReference1.StepGoalsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StepGoalsSoapClient : System.ServiceModel.ClientBase<FitnessApplication.StepGoalsReference1.StepGoalsSoap>, FitnessApplication.StepGoalsReference1.StepGoalsSoap {
        
        public StepGoalsSoapClient() {
        }
        
        public StepGoalsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StepGoalsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StepGoalsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StepGoalsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FitnessApplication.StepGoalsReference1.RecommendedStepsResponse FitnessApplication.StepGoalsReference1.StepGoalsSoap.RecommendedSteps(FitnessApplication.StepGoalsReference1.RecommendedStepsRequest request) {
            return base.Channel.RecommendedSteps(request);
        }
        
        public string RecommendedSteps(int age, string activityLevel) {
            FitnessApplication.StepGoalsReference1.RecommendedStepsRequest inValue = new FitnessApplication.StepGoalsReference1.RecommendedStepsRequest();
            inValue.Body = new FitnessApplication.StepGoalsReference1.RecommendedStepsRequestBody();
            inValue.Body.age = age;
            inValue.Body.activityLevel = activityLevel;
            FitnessApplication.StepGoalsReference1.RecommendedStepsResponse retVal = ((FitnessApplication.StepGoalsReference1.StepGoalsSoap)(this)).RecommendedSteps(inValue);
            return retVal.Body.RecommendedStepsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FitnessApplication.StepGoalsReference1.RecommendedStepsResponse> FitnessApplication.StepGoalsReference1.StepGoalsSoap.RecommendedStepsAsync(FitnessApplication.StepGoalsReference1.RecommendedStepsRequest request) {
            return base.Channel.RecommendedStepsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FitnessApplication.StepGoalsReference1.RecommendedStepsResponse> RecommendedStepsAsync(int age, string activityLevel) {
            FitnessApplication.StepGoalsReference1.RecommendedStepsRequest inValue = new FitnessApplication.StepGoalsReference1.RecommendedStepsRequest();
            inValue.Body = new FitnessApplication.StepGoalsReference1.RecommendedStepsRequestBody();
            inValue.Body.age = age;
            inValue.Body.activityLevel = activityLevel;
            return ((FitnessApplication.StepGoalsReference1.StepGoalsSoap)(this)).RecommendedStepsAsync(inValue);
        }
    }
}
